#!/bin/bash

set -e

read -p "Name: " name
read -p "Email: " email

git config --global user.name "$name"
git config --global user.email "$email"

ssh-keygen -t ed25519 -C "$email" -f "$HOME/.ssh/id_ed25519" -N ""
eval "$(ssh-agent -s)"
ssh-add "$HOME/.ssh/id_ed25519"

echo ""
echo "Add this key to https://github.com/settings/ssh/new"
echo ""
cat "$HOME/.ssh/id_ed25519.pub"
echo ""
